### PR TITLE
New Update 3.1.0 based TWRP 3.5.2

### PR DESCRIPTION
**Pull request by qih47**

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@qih47 you can remove `.circleci/config.yml`

**Comment by qih47** [comment]
how to remove that sir?

**Comment by qih47** [comment]
I thought I deleted it

**Comment by manjotsidhu** [comment]
@mdraza110 can you merge this ?

**Comment by qih47** [comment]
ah wait I think I did something wrong

**Pull request closed without merging**
